# File generated from our OpenAPI spec
defmodule Stripe.Params.V2.Core.AccountUpdateParams do
  @moduledoc "Parameters for account update."

  @typedoc """
  * `account_token` - The account token generated by the account token api.
  * `configuration` - An Account Configuration which allows the Account to take on a key persona across Stripe products.
  * `contact_email` - The default contact email address for the Account. Required when configuring the account as a merchant or recipient.
  * `contact_phone` - The default contact phone for the Account.
  * `dashboard` - A value indicating the Stripe dashboard this Account has access to. This will depend on which configurations are enabled for this account. Possible values: `express`, `full`, `none`.
  * `defaults` - Default values to be used on Account Configurations.
  * `display_name` - A descriptive name for the Account. This name will be surfaced in the Stripe Dashboard and on any invoices sent to the Account.
  * `identity` - Information about the company, individual, and business represented by the Account.
  * `include` - Additional fields to include in the response.
  * `metadata` - Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
  """
  @type t :: %__MODULE__{
          account_token: String.t() | nil,
          configuration: map() | nil,
          contact_email: String.t() | nil,
          contact_phone: String.t() | nil,
          dashboard: String.t() | nil,
          defaults: map() | nil,
          display_name: String.t() | nil,
          identity: map() | nil,
          include: [String.t()] | nil,
          metadata: map() | nil
        }

  defstruct [
    :account_token,
    :configuration,
    :contact_email,
    :contact_phone,
    :dashboard,
    :defaults,
    :display_name,
    :identity,
    :include,
    :metadata
  ]

  defmodule Configuration do
    @moduledoc "Nested parameters."

    @typedoc """
    * `customer` - The Customer Configuration allows the Account to be charged.
    * `merchant` - Enables the Account to act as a connected account and collect payments facilitated by a Connect platform. You must onboard your platform to Connect before you can add this configuration to your connected accounts. Utilize this configuration when the Account will be the Merchant of Record, like with Direct charges or Destination Charges with on_behalf_of set.
    * `recipient` - The Recipient Configuration allows the Account to receive funds. Utilize this configuration if the Account will not be the Merchant of Record, like with Separate Charges & Transfers, or Destination Charges without on_behalf_of set.
    """
    @type t :: %__MODULE__{
            customer: map() | nil,
            merchant: map() | nil,
            recipient: map() | nil
          }
    defstruct [:customer, :merchant, :recipient]
  end

  defmodule Defaults do
    @moduledoc "Nested parameters."

    @typedoc """
    * `currency` - Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
    * `locales` - The Account's preferred locales (languages), ordered by preference.
    * `profile` - Account profile information.
    * `responsibilities` - Default responsibilities held by either Stripe or the platform.
    """
    @type t :: %__MODULE__{
            currency: String.t() | nil,
            locales: [String.t()] | nil,
            profile: map() | nil,
            responsibilities: map() | nil
          }
    defstruct [:currency, :locales, :profile, :responsibilities]
  end

  defmodule Identity do
    @moduledoc "Nested parameters."

    @typedoc """
    * `attestations` - Attestations from the identity's key people, e.g. owners, executives, directors, representatives.
    * `business_details` - Information about the company or business.
    * `country` - The country in which the account holder resides, or in which the business is legally established. This should be an [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code.
    * `entity_type` - The entity type. Possible values: `company`, `government_entity`, `individual`, `non_profit`.
    * `individual` - Information about the individual represented by the Account. This property is `null` unless `entity_type` is set to `individual`.
    """
    @type t :: %__MODULE__{
            attestations: map() | nil,
            business_details: map() | nil,
            country: String.t() | nil,
            entity_type: String.t() | nil,
            individual: map() | nil
          }
    defstruct [:attestations, :business_details, :country, :entity_type, :individual]
  end
end
